include: package:lints/recommended.yaml

linter:
  rules:
    # Style rules
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names
    - directives_ordering
    - lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures

    # Documentation rules
    - package_api_docs
    - public_member_api_docs
    - comment_references

    # Usage rules
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes

    # Design rules
    - use_rethrow_when_possible
    - use_to_and_as_if_applicable
    - avoid_implementing_value_types
    - avoid_classes_with_only_static_members
    - avoid_private_typedef_functions

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: info
    deprecated_member_use: warning
    dead_code: warning
